name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    outputs:
      repo_owner_lower: ${{ steps.repo_owner.outputs.repo_owner_lower }}

    steps:
      - uses: actions/checkout@v2

      - name: Convert repository owner to lowercase
        id: repo_owner
        run: echo "::set-output name=repo_owner_lower::$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CICD_TOKEN }}

      - name: Build and push app container image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ steps.repo_owner.outputs.repo_owner_lower }}/telegram-bot-nodejs:latest

  deploy-to-ec2:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            echo "${{ secrets.CICD_TOKEN }}" | sudo docker login ghcr.io -u ${{ github.actor }} --password-stdin
            cd ~/telegram-bot-nodejs
            sudo git pull
            sudo docker ps -a | grep nodeapp && docker rm -f nodeapp || true # Удаляем контейнер /nodeapp, если он существует
            sudo docker-compose pull app
            sudo docker-compose down
            sudo docker-compose up -d --force-recreate --no-deps app
