name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2 and Restart Docker Container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          cd telegram-bot-nodejs
          git pull origin main
          # Остановка и удаление существующего контейнера, если он существует
          sudo docker stop nest-gpt || true
          sudo docker rm nest-gpt || true
          # Пересборка образа
          sudo docker build -t nest-gpt .
          # Запуск контейнера с новым образом
          sudo docker run -d --name nest-gpt -p 3000:3000 nest-gpt

